### ISSUE TITLE
Re-entrancy vector

### ISSUE THREAD

**Issue by htadashi** [indexpool/contracts#10]
Slither detected a re-entrancy in this code (due to OpenZeppelin's `safeMint` calling `onERC721received`):
https://github.com/indexpool/indexpool-contracts/blob/5ae746f25a4d6a8f3865e6dfcd34e4b1afe26651/contracts/nft/IndexPoolNFT.sol#L36-L53

As far I can tell, this currently doesn't pose any safety problem in IndexPoolNFT.sol, but if the deployer calls a malicious smart contract and IndexPoolNFT is further extended in the future, maybe is best to consider using [check-effects-interaction pattern](https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html) for avoiding [(cross-function) reentrancy problems](https://consensys.github.io/smart-contract-best-practices/known_attacks/#cross-function-reentrancy).

**Comment by joaoavf** [comment]
Attempted fix @ c4e34d8c58e34c9495a0e697a948765de1628e82
