### ISSUE TITLE
Possible loss of precision

### ISSUE THREAD

**Issue by htadashi** [indexpool/contracts#9]
Hey friends, congrats again on building this cool product! :)

[Slither](https://github.com/crytic/slither) detected a possible [loss of precision](https://github.com/crytic/slither/wiki/Detector-Documentation#divide-before-multiply) in `calculateQuotaPrice` function:
https://github.com/indexpool/indexpool-contracts/blob/287bb222c72501a96191144edf17ee1e3ef4a42f/contracts/Pool.sol#L346-L351

Suggested fix:
```
// Decide how much to buy
(quotaPrice, amounts) = calculateQuotaPrice(allocation, paths, tokens);

for (uint8 i = 0; i < amounts.length; i++) {
	amounts[i] = (amounts[i] * freeAmount) / quotaPrice;
}
```

**Comment by joaoavf** [comment]
Thanks Tadashi!!

Fixed @ dd9537c0d24102a142673a3c8cb8ef1aed1d6565
